-- MySQL Script generated by MySQL Workbench
-- Wed Mar 14 15:24:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Card
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Card
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Card` DEFAULT CHARACTER SET utf8 ;
USE `Card` ;

-- -----------------------------------------------------
-- Table `Card`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Card`.`student` (
  `idstudent` INT NOT NULL,
  `fullname` VARCHAR(45) NULL,
  `birthdat` DATE NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
